name: AWS Budget
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  create_budget:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::462753922172:role/GitHub

      - name: checkout
        uses: actions/checkout@v4

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform fmt
        id: fmt
        run: terraform -chdir=./terraform fmt -check

      - name: terraform init
        id: init
        run: terraform -chdir=./terraform init -input=false

      - name: terraform validate
        id: validate
        run: terraform -chdir=./terraform validate -no-color

      - name: terraform plan
        id: plan
        run: terraform -chdir=./terraform plan -no-color -input=false

      - name: terraform apply
        id: apply
        run: terraform -chdir=./terraform apply -no-color -input=false -auto-approve
